version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: mongo_OZmap
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo_OZmap_data:/data/db

volumes:
  mongo_OZmap_data:
